enablePrePostScripts: false
nodeLinker: hoisted
verifyDepsBeforeRun: false
ignoreScripts: true
allowBuilds:
  "@parcel/watcher": false
  core-js: false
  edgedriver: false
  es5-ext: false
  esbuild: false
  geckodriver: false
  meta-json-schema: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - dayjs@1.11.21
